### ISSUE TITLE
BUG: Regex "B(AAC)?AAD" can't capture input "BAAD"

### ISSUE THREAD

**Issue by gogo9th** [mattbucknall/subreg#5]
This error for (* and ?) occurs because the program doesn't rewind the input when * or ? doesn't match initially. So we need checkpoints not only for the regex, also for the input. 

To fix this, inside function static int parse_repetition(state_t* state), at at the very beginning:

`const char* check_point = state->input; `

and inside the if ( rc == '?' ) block, add:
```
      if ( !is_match_result(result) ) /* ADD !!! */
         state->input = check_point;
```

and inside the    else if ( rc == '*' )   {      if ( !is_match_result(result) ) block, add:

`         state->input = check_point;`

**Comment by mattbucknall** [comment]
Fixed in a443963409b824c9767639e03e770a591e5777dc
